from pydantic_ai import Agent
from pydantic_ai.models.gemini import GeminiModel
from src.data_models import Recommendation
from src.db.chroma import movie_overviews, user_reviews
from src.db.taste_profile import get_latest_taste_profile
from src.db.reviews import get_review_by_tmdb_id
from src.agents.model import model
from src.agents.mood_agent import interpret_mood
from src.clients.tmdb import get_movie
from pydantic import BaseModel
from typing import List

class RecommendationList(BaseModel):
    recommendations: List[Recommendation]

recommendation_agent = Agent(
    model=model,
    output_type=RecommendationList,
    system_prompt="""
    You are a movie recommendation agent. You have access to tools to search movies,
    fetch ratings, and retrieve the user's taste profile.
    
    These are the tools you have at your disposal:
    - query_movies(query: str, n_results: int): Queries ChromaDB for movies matching the query. The query can be a mood, genre, or any text that can help find relevant movies.
    - fetch_tmdb_ratings(tmdb_id: str): Fetches TMDB ratings and other relevant info for a given tmdb_id. This can be used to re-rank movies based on their ratings and popularity.
    - get_taste_profile(): Gets the taste profile for the user. This should be used as a tiebreaker when there are multiple movies with similar ratings or when the mood query is not specific enough.
    - get_past_review(tmdb_id: str): Gets the user's past review for a given movie. This can provide additional context about the user's preferences and help you make a more informed recommendation.
    - query_reviews(query: str, n_results: int): Queries ChromaDB for reviews of a given movie. This can provide additional context about the movie and help you make a more informed recommendation.

    Before you run, there is a pre-processing step where the user's raw input is interpreted into a mood query. 
    This mood query is designed to capture the user's current emotional state and preferences for the movie they want to watch. 
    The mood query is generated by a separate mood agent that analyzes the user's input and extracts relevant information to create a structured query.
    
    The mood query always takes priority over the taste profile.
    If there is a conflict between the mood and profile, proceed with the mood and note it in conflict_note.
    Return a single confident recommendation with clear reasoning.

    Please return up to 10 recommendations. Never return only one recommendation, even if you are very confident about it. The more the better, as long as they are good recommendations.
    """
)

@recommendation_agent.tool_plain
def query_movies(query: str, n_results: int = 10) -> list[dict]:
    """
    Queries ChromaDB with a the query arg in the function defintion.
    This query can be generated by the you, the LLM, or can directly be the query the user typed in.

    Args:
        - query: the query to search for in ChromaDB. This can be a mood query, a genre, or any text that can be used to find relevant movies.
        - n_results: the number of results to return from ChromaDB. You can adjust this number based on how many candidates you want to consider for recommendation.
    """
    print(f"Querying movies with: {query}")
    results = movie_overviews.query(
        query_texts=[query],
        n_results=n_results
    )

    movies = []
    for i, metadata in enumerate(results["metadatas"][0]):
        movies.append({
            **metadata,
            "overview": results["documents"][0][i]
        })
    return movies

@recommendation_agent.tool_plain
def fetch_tmdb_ratings(tmdb_id: str) -> dict:
    """
    Fetches TMDB ratings and other relevant info for a given tmdb_id. This can be used to re-rank movies based on their ratings and popularity.

    Args:
    - tmdb_id: the TMDB ID of the movie to fetch ratings for. This should be a string.
    """

    print("Fetching TMDB ratings for:", tmdb_id)
    data = get_movie(int(tmdb_id))
    return {
        "rating": data["vote_average"],
        "popularity": data["popularity"],
        "runtime": data["runtime"]
    }

@recommendation_agent.tool_plain
def get_taste_profile() -> str:
    """
    Gets the taste profile for the user. This should be used as a tiebreaker when there are multiple movies with similar ratings or when the mood query is not specific enough. The taste profile can provide additional context about the user's preferences and help you make a more informed recommendation.
    """
    print("Retrieving latest taste profile")    
    profile = get_latest_taste_profile()
    return profile.model_dump_json() if profile else "No taste profile yet"

@recommendation_agent.tool_plain
def get_past_review(tmdb_id) -> str:
    """
    Gets the user's past review for a given movie. This can provide additional context about the user's preferences and help you make a more informed recommendation.

    Args:
    - tmdb_id: the TMDB ID of the movie to fetch the past review for. This should be a string.
    """
    print("Retrieving past review for TMDB ID:", tmdb_id)

    past_reviews = get_review_by_tmdb_id(tmdb_id)
    
    if not past_reviews:
        return "No past review for this movie"

    return past_reviews.model_dump_json()

@recommendation_agent.tool_plain
def query_reviews(query, n_results) -> list[dict]:
    """
    Queries ChromaDB for reviews of a given movie. This can provide additional context about the movie and help you make a more informed recommendation.
    
    Args:
    - query: the query to search for in ChromaDB. This can be the movie title, a mood, or any text that can be used to find relevant reviews.
    - n_results: the number of results to return from ChromaDB. You can adjust this number based on how many reviews you want to consider for recommendation.
    """
    print(f"Querying movies with: {query}")
    results = user_reviews.query(
        query_texts=[query],
        n_results=n_results
    )

    reviews = []
    for i, metadata in enumerate(results["metadatas"][0]):
        reviews.append({
            **metadata,
            "review_text": results["documents"][0][i]
        })
    
    return reviews



async def get_recommendation(raw_input: str) -> RecommendationList:
    taste_profile = get_latest_taste_profile()

    mood_query = await interpret_mood(raw_input, taste_profile)

    query_text = f"""
        Mood query: {mood_query.model_dump_json()}
        User taste profile: {taste_profile.model_dump_json() if taste_profile else "None"}
    """
    result = await recommendation_agent.run(query_text)
    return result.output
